version: '3'
services:
  postgres:
    image: parrotstream/postgres:10.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass

    privileged: true
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
